import './globals.css'
import type { Metadata } from 'next'
import { Manrope } from 'next/font/google'
import NavBar from './components/navBar'
import { Suspense } from 'react'

const manrope = Manrope({
  subsets: ['latin'],
  variable: '--font-manrope',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={manrope.variable}>
      <body className="flex flex-col font-manrope">
        <NavBar />
          <div className="p-4">        
            {children}
          </div>
      </body>
    </html>
  )
}
